name: "Composite Deploy Actions"
description: "Common Deploy Actions to AKS"

inputs:
  akv_secrets:
    description: "Secrets to retrieve from Azure Key Vault"
    required: true
  idp-admin-password:
    description: "Name of env for idp admin password"
    required: true
  idp-admin-username:
    description: "Name of env for idp admin username"
    required: true
  rabbitmq-password:
    description: "rabbitmq password"
    required: false
  db-connection:
    description: "Database connection string"
    required: false

runs:
  using: "composite"
  steps:
  - name: 'Get secrets'
    id: azure-keyvault-secrets
    shell: bash
    run: |
      echo ./${{env.SERVICE_DIR}}/${{env.SERVICE}}.yml
      secrets_get=${{ inputs.akv_secrets }}
      for secret_get in ${secrets_get[@]}
      do
        value=$(az keyvault secret show --name $secret_get --vault-name kvcontainerdeploydemo --query value --output tsv)
        echo "::add-mask::$value"
        echo "$secret_get=$value" >> $GITHUB_OUTPUT
      done    
  
  - name: Replace tokens for Service Config
    uses: cschleiden/replace-tokens@v1
    with:
      files: ./${{env.SERVICE_DIR}}/${{env.SERVICE}}.yml
    env:
      ${{ inputs.idp-admin-password }}: ${{ steps.azure-keyvault-secrets.outputs.rabbitmqpassword }}
      ${{ inputs.idp-admin-username }}: ${{ steps.azure-keyvault-secrets.outputs.admin-user-name }}
      ${{ inputs.rabbitmq-password }}: ${{ steps.azure-keyvault-secrets.outputs.rabbitmqpassword }}
      ${{ inputs.db-connection }}: ${{ steps.azure-keyvault-secrets.outputs.dbconnection }}
      
     