# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: buyerbff-deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "buyerbff-build" ]
    branches: [ "main" ]
    types: [ completed ]
      
env:
  SERVICE: buyer-bff
  SERVICE_DIR: FS.TechDemo.BuyerBFF
  ACR_LOGON_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io
  IMAGE_NAME: ${{ secrets.ACR_NAME }}.azurecr.io/buyer-bff:${{ github.sha }}
  
jobs:
  deploy-to-aks:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      NAMESPACE: dev
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/deploy
        with:
          akv_secrets: (rabbitmqpassword admin-user-name dbconnection)
          idp-admin-password: idp-admin-password
          idp-admin-username: idp-admin-username
          rabbitmq-password: rabbitmq-password
          db-connection: db-connection
    
    
