# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: buyerbff

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - FS.TechDemo.BuyerBFF/**
      - FS.TechDemo.Shared/**
      - .github/workflows/buyerbff.yml
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - FS.TechDemo.BuyerBFF/**
      - FS.TechDemo.Shared/**
      - .github/workflows/buyerbff.yml

env:
  SERVICE: buyerbff
  IMAGE: buyer-bff
  
jobs:
  BuildContainersForPR_Linux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/build
        with:
          service: ${{ env.SERVICE }}
          registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
  
  BuildLinux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/build-push
        with:
          service: ${{ env.SERVICE }}
          registry_host: ${{ secrets.REGISTRY_HOST }}
          registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
          image_name: ${{ env.IMAGE }}
          registry_username: ${{ secrets.USERNAME }}
          registry_password: ${{ secrets.PASSWORD }}      