name: buyerbff-build

on:
  workflow_dispatch:
  push:
    branches: [ "main"]
    paths:
      - FS.TechDemo.BuyerBFF/**
      - FS.TechDemo.Shared/**
      - .github/workflows/buyerbff-build.yml
      - .github/workflows/buyerbff-deploy.yml

env:
  SERVICE: buyer-bff
  SERVICE_DIR: FS.TechDemo.BuyerBFF
  IMAGE: buyer-bff
  ACR_LOGON_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io
  IMAGE_NAME: ${{ secrets.ACR_NAME }}.azurecr.io/buyer-bff:${{ github.sha }}
  
jobs:
  
  build-image:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGON_SERVER }}
          username: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          password: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
      - run: docker build -t ${{ env.IMAGE_NAME }} -f ./${{ env.SERVICE_DIR }}/Dockerfile .
      - run: docker push ${{ env.IMAGE_NAME }}        
      