name: order-service-build

on:
  create:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (buyer-d, buyer-q, szfg-q, szfg)"
        required: true
        default: buyer-d
        
  push:
    branches: [ "main"]
    paths:
      - FS.TechDemo.OrderService/**
      - FS.TechDemo.Shared/**
      - .github/workflows/order-service-build.yml
      - .github/workflows/order-service-deploy.yml
      - .github/workflows/composite/**


env:
  SERVICE: order-service
  SERVICE_DIR: FS.TechDemo.OrderService
  ACR_LOGON_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io
  IMAGE_NAME: ${{ secrets.ACR_NAME }}.azurecr.io/order-service:${{ github.sha }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: "Set environment if not workflow dispatch"
        run: |
          if [ -z "${{ github.event.inputs.environment }}" ]; then
            echo "environment=buyer-d" >> $GITHUB_ENV
          else
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          fi
      - run: echo $environment
        
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: deploy-artifact
          path: $GITHUB_ENV
          
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGON_SERVER }}
          username: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          password: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
      - run: docker build -t ${{ env.IMAGE_NAME }} -f ./${{ env.SERVICE_DIR }}/Dockerfile .
      - run: docker push ${{ env.IMAGE_NAME }} 
  
  deploy-to-aks:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: deploy-artifact

      - run: echo $environment
      - run: echo ${{env.environment}}
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: actions/checkout@v3

      - uses: ./.github/workflows/composite/deploy
        with:
          aks-name: ${{secrets.AKS_NAME}}
          azure-credentials: ${{secrets.AZURE_CREDENTIALS}}
          aks-resource-group: ${{secrets.AKS_RESOURCE_GROUP}}
          aks-secret: ${{secrets.AKS_SECRET}}
          service-principal-id: ${{secrets.SERVICE_PRINCIPAL_ID}}
          service-principal-password: ${{secrets.SERVICE_PRINCIPAL_PASSWORD}}
          akv_secrets: (rabbitmqpassword admin-user-name dbconnection)        
          