# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: order-service-deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "order-service-build" ]
    branches: [ "main" ]
    types: [ completed ]
      
env:
  SERVICE: order-service
  SERVICE_DIR: FS.TechDemo.OrderService
  IMAGE: order-service
  ACR_LOGON_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io
  IMAGE_NAME: ${{ secrets.ACR_NAME }}.azurecr.io/order-service:${{ github.sha }}
  
jobs:
  deploy-to-aks:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      NAMESPACE: ${{ github.event.inputs.namespace }}
    steps:
      - run: echo env.NAMESPACE
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - uses: actions/checkout@v3
        
      - uses: ./.github/workflows/composite/deploy
        with:
          aks-name: ${{secrets.AKS_NAME}}
          azure-credentials: ${{secrets.AZURE_CREDENTIALS}}
          aks-resource-group: ${{secrets.AKS_RESOURCE_GROUP}}
          aks-secret: ${{secrets.AKS_SECRET}}
          service-principal-id: ${{secrets.SERVICE_PRINCIPAL_ID}}
          service-principal-password: ${{secrets.SERVICE_PRINCIPAL_PASSWORD}}
          akv_secrets: (rabbitmqpassword admin-user-name dbconnection)
          
