name: order-service-build

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "Environment (buyer-d, buyer-q, szfg-q, szfg)"
        required: true
        default: "buyer-d"
        
  push:
    branches: [ "main"]
    paths:
      - FS.TechDemo.OrderService/**
      - FS.TechDemo.Shared/**
      - .github/workflows/order-service-build.yml
      - .github/workflows/order-service-deploy.yml
      - .github/workflows/composite/**

env:
  SERVICE: order-service
  SERVICE_DIR: FS.TechDemo.OrderService
  ACR_LOGON_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io
  IMAGE_NAME: ${{ secrets.ACR_NAME }}.azurecr.io/order-service:${{ github.sha }}
  NAMESPACE: ${{ github.event.inputs.namespace }}
  
jobs:
  build-image:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - run: echo ${{env.NAMESPACE}} 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGON_SERVER }}
          username: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          password: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
      - run: docker build -t ${{ env.IMAGE_NAME }} -f ./${{ env.SERVICE_DIR }}/Dockerfile .
      - run: docker push ${{ env.IMAGE_NAME }}        
          